from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path
from typing import Tuple


SERVICE_NAME = "argus.service"


def user_unit_path(service_name: str = SERVICE_NAME) -> Path:
    return Path.home() / ".config" / "systemd" / "user" / service_name


def _find_exec_start(log_path: str) -> str:
    """
    Prefer the installed 'argus' executable (pipx / pip / distro),
    fallback to 'python -m argus.cli' when needed.
    """
    exe = shutil.which("argus")
    if exe:
        exe_path = str(Path(exe).resolve())
        return f"{exe_path} run --log-path {log_path}"

    # fallback (should be rare): use the python running this command
    py = str(Path(sys.executable).resolve())
    return f"{py} -m argus.cli run --log-path {log_path}"


def render_user_unit(
    *,
    log_path: str = "/var/log/auth.log",
    description: str = "ARGUS Eye (security + health monitor)",
) -> str:
    exec_start = _find_exec_start(log_path)

    # Notes:
    # - %t = XDG_RUNTIME_DIR (/run/user/UID). This helps DBus notifications in most setups.
    # - DBUS_SESSION_BUS_ADDRESS is commonly unix:path=%t/bus for user session bus.
    return f"""# This unit is generated by `argus install-service`
# Do not edit by hand unless you know what you're doing.

[Unit]
Description={description}
After=default.target

[Service]
Type=simple

# Run from $HOME (not tied to any repo path)
WorkingDirectory=%h

# ExecStart uses the installed argus entrypoint (pipx-friendly)
ExecStart={exec_start}

Restart=on-failure
RestartSec=2

# PATH: include user-local bins (pipx puts scripts in ~/.local/bin)
Environment=PATH=%h/.local/bin:/usr/local/bin:/usr/bin:/bin

# DBus/desktop session basics (best-effort)
Environment=XDG_RUNTIME_DIR=%t
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=%t/bus

StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
"""


def install_user_unit(
    *,
    log_path: str = "/var/log/auth.log",
    force: bool = False,
) -> Tuple[str, str]:
    """
    Install (or update) the systemd --user unit.
    Returns (unit_path, action) where action is 'installed'|'updated'|'kept'.
    """
    unit_path = user_unit_path()
    unit_path.parent.mkdir(parents=True, exist_ok=True)

    content = render_user_unit(log_path=log_path)

    if unit_path.exists():
        old = unit_path.read_text(encoding="utf-8", errors="ignore")
        if old == content:
            return str(unit_path), "kept"
        if not force:
            # keep existing, user must confirm overwrite
            return str(unit_path), "kept"
        unit_path.write_text(content, encoding="utf-8")
        return str(unit_path), "updated"

    unit_path.write_text(content, encoding="utf-8")
    return str(unit_path), "installed"
